### ISSUE TITLE
Consider improving validation of meter IDs

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-meter-usage-reporter#14]
https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/main/lib/meters.js#L498

Due to lack of validation on the meter ID itself, an HTTP request to the following URL can be generated: `https://meter.stable.veres.tools/meters/undefined/usage`

It would be nice to have an informative error message that the meter ID is invalid in this case.

```
{
  "insertId": "6373c47e0003d171be403e53",
  "jsonPayload": {
    "@message": "error",
    "@fields": {
      "error": {
        "type": "Error",
        "message": "An error occurred.",
        "name": "Error",
        "stack": "Error: An error occurred.\n    at file:///home/node/app/node_modules/@bedrock/express/lib/index.js:329:13\n    at Layer.handle_error (/home/node/app/node_modules/express/lib/router/layer.js:71:5)\n    at trim_prefix (/home/node/app/node_modules/express/lib/router/index.js:326:13)\n    at /home/node/app/node_modules/express/lib/router/index.js:286:9\n    at Function.process_params (/home/node/app/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/node/app/node_modules/express/lib/router/index.js:280:10)\n    at next (/home/node/app/node_modules/express/lib/router/route.js:129:14)\n    at Layer.handle_error (/home/node/app/node_modules/express/lib/router/layer.js:67:12)\n    at next (/home/node/app/node_modules/express/lib/router/route.js:142:13)\n    at Layer.handle_error (/home/node/app/node_modules/express/lib/router/layer.js:67:12)",
        "cause": {
          "stack": "HTTPError: An unspecified error occurred.\n    at fn (file:///home/node/app/node_modules/ky/distribution/core/Ky.js:94:29)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Ky._retry (file:///home/node/app/node_modules/ky/distribution/core/Ky.js:173:20)\n    at async _handleResponse (file:///home/node/app/node_modules/@digitalbazaar/http-client/lib/httpClient.js:100:16)\n    at async _getUsage (file:///home/node/app/node_modules/@bedrock/meter-usage-reporter/lib/meters.js:498:20)\n    at async Module.hasAvailable (file:///home/node/app/node_modules/@bedrock/meter-usage-reporter/lib/meters.js:234:41)\n    at async file:///home/node/app/node_modules/@bedrock/kms-http/lib/http.js:66:37",
          "response": {
            "size": 0
          },
          "name": "HTTPError",
          "type": "HTTPError",
          "data": {
            "type": "OperationError",
            "message": "An unspecified error occurred.",
            "name": "OperationError"
          },
          "status": 500,
          "message": "An unspecified error occurred.",
          "requestUrl": "https://meter.stable.veres.tools/meters/undefined/usage",
          "options": {
            "retry": {
              "maxRetryAfter": null,
              "methods": [
                "get",
                "put",
                "head",
                "delete",
                "options",
                "trace"
              ],
              "afterStatusCodes": [
                413,
                429,
                503
              ],
              "limit": 2,
              "statusCodes": [
                408,
                413,
                429,
                500,
                502,
                503,
                504
              ]
            },
            "prefixUrl": "",
            "headers": {},
            "timeout": 10000,
            "hooks": {
              "beforeError": [],
              "beforeRetry": [],
              "beforeRequest": [],
              "afterResponse": []
            },
            "throwHttpErrors": true,
            "method": "GET",
            "agent": {},
            "credentials": "same-origin",
            "signal": {}
          },
          "request": {
            "counter": 0,
            "insecureHTTPParser": false,
            "follow": 20,
            "agent": {},
            "compress": true,
            "highWaterMark": 16384,
            "size": 0
          }
        },
        "details": null
      },
      "workerPid": 13,
      "workerId": "3d4e4b96505d4c55",
      "level": "error",
      "module": "express"
    },
    "@timestamp": "2022-11-15T16:55:26.245Z"
  },
  "resource": {
    "type": "cloud_run_revision",
    "labels": {
      "service_name": "us-east1-veres-kms",
      "project_id": "veres-stable4-kms",
      "location": "us-east1",
      "configuration_name": "us-east1-veres-kms",
      "revision_name": "us-east1-veres-kms-rl65x"
    }
  },
  "timestamp": "2022-11-15T16:55:26.250225Z",
  "labels": {
    "instanceId": "0074e2ccb2b3bf40735d3274b6fc01c856295fb901d160ef895f46669ff36b1e9ca489139b360f7f91bed28e899785fe5add8661d7aec16fab8635d2758951454f"
  },
  "logName": "projects/veres-stable4-kms/logs/run.googleapis.com%2Fstdout",
  "receiveTimestamp": "2022-11-15T16:55:26.256431582Z"
}
```

**Comment by mattcollier** [comment]
Should be resolved by PRs in other modules.  Will reopen if necessary.
